#!/bin/sh

case "$1" in
	start)
		cd /lib/modules/$(uname -r)/extra
		scull_load
		module_load faulty
		modprobe hello
		;;
	stop)
		cd /lib/modules/$(uname -r)/extra
		scull_unload
		module_unload faulty
		rmmod hello
		;;

	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
